# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Deploy after the build finished
      run: |
        # abort on errors
        set -e

        # build
        npm run build

        # navigate into the build output directory
        cd dist

        # if you are deploying to a custom domain
        echo 'https://ryanyuyu.github.io/dnd-encounter-builder/' > CNAME

        git init
        git add -A
        git commit -m 'deploy'

        # if you are deploying to https://<USERNAME>.github.io
        # git push -f git@github.com:<USERNAME>/<USERNAME>.github.io.git master

        # if you are deploying to https://<USERNAME>.github.io/<REPO>
        git push -f git@github.com:ryanyuyu.github.io/dnd-encounter-builder.git master:gh-pages

        cd -
